### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by r4dian** [thormagnusson/scoring#1]
Hope you don't mind a message on here, the link in the Preface no longer works. (Apparently the whole gitbooks site has been through 3 iterations since then, and this is considered a "legacy" book ?!)

Anyway, all the images are missing in the gitbooks site, but also in this repo.

**Comment by thormagnusson** [comment]
Hi r4dian,

I can't remember why I decided not to use Gitbooks, but I moved my book to Leanpub:

https://leanpub.com/ScoringSound

**Comment by r4dian** [comment]
Ah I see. Thanks.
